/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.bancodados;

import BancoDados.Banco;
import BancoDados.GerenciadorBanco;
import java.util.ArrayList;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme.machado
 */
public class AlterarBanco extends javax.swing.JFrame {

    ArrayList<Banco> bancos;
    private Banco atual;

    private static AlterarBanco instancia;

    /**
     * Creates new form AlterarBanco
     */
    public AlterarBanco() {

        initComponents();
        atualizar();
        bancosTabela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index = ((DefaultListSelectionModel) e.getSource()).getMaxSelectionIndex();
                if (index < 0 || index > bancos.size()) {
                    return;
                }
                atual = bancos.get(index);
                atualizarCampos();
            }
        });
    }

    /**
     *
     * @return
     */
    public static AlterarBanco getInstancia() {
        if (instancia == null) {
            instancia = new AlterarBanco();
        }

        return instancia;
    }

    private void atualizar() {
        atualizarArray();
        atualizarTabela();
    }

    private void atualizarArray() {
        if (bancos != null) {
            bancos.clear();
        }
        bancos = Configuracao.Configuracao.INSTANCIA.getBancos();
    }

    private void atualizarTabela() {

        if (bancosTabela == null || bancos == null) {

            return;
        }
        DefaultTableModel model = (DefaultTableModel) bancosTabela.getModel();
        model.setRowCount(0);
        bancos.forEach(s -> {
            model.addRow(new Object[]{s.getCAMINHO(), s.getUSUARIO(), s.getSENHA(), s.getNOME(), s.isATIVO(),s.isPMWEB()});
        });
    }

    private void atualizarCampos() {
        caminhoCampo.setText(atual.getCAMINHO());
        usuarioCampo.setText(atual.getUSUARIO());
        senhaCampo.setText(atual.getSENHA());
        nomeCampo.setText(atual.getNOME());
        ativoCampo.setSelected(atual.isATIVO());
        pmWebBox.setSelected(atual.isPMWEB());
    }

    private void atualizarAtual() {
        atual.setCAMINHO(caminhoCampo.getText());
        atual.setUSUARIO(usuarioCampo.getText());
        atual.setSENHA(senhaCampo.getText());
        atual.setNOME(nomeCampo.getText());
        atual.setATIVO(ativoCampo.isSelected());
        atual.setPMWEB(pmWebBox.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bancosTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        caminhoCampo = new javax.swing.JTextField();
        usuarioCampo = new javax.swing.JTextField();
        senhaCampo = new javax.swing.JTextField();
        nomeCampo = new javax.swing.JTextField();
        ativoCampo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pmWebBox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar");
        setResizable(false);

        bancosTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caminho", "Usuario", "Senha", "Nome", "Ativo", "PmWeb"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bancosTabela);

        jLabel1.setText("Caminho");

        caminhoCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caminhoCampoMouseClicked(evt);
            }
        });

        ativoCampo.setText("Ativo");

        jLabel2.setText("Usuario");

        jLabel3.setText("Senha");

        jLabel4.setText("Nome");

        pmWebBox.setText("PmWeb");

        jMenu1.setText("Tabela");

        jMenuItem3.setText("Salvar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caminhoCampo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usuarioCampo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(senhaCampo)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeCampo)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ativoCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pmWebBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caminhoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ativoCampo)
                    .addComponent(pmWebBox))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caminhoCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caminhoCampoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            JFileChooser file = new JFileChooser();
            file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                caminhoCampo.setText(file.getSelectedFile().getAbsolutePath());
            }
        }
    }//GEN-LAST:event_caminhoCampoMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        atualizarAtual();
        GerenciadorBanco.INSTANCIA.fechar();
        Configuracao.Configuracao.INSTANCIA.atualizarBanco(atual);
        GerenciadorBanco.INSTANCIA.iniciar();
        atualizar();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativoCampo;
    private javax.swing.JTable bancosTabela;
    private javax.swing.JTextField caminhoCampo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JCheckBox pmWebBox;
    private javax.swing.JTextField senhaCampo;
    private javax.swing.JTextField usuarioCampo;
    // End of variables declaration//GEN-END:variables
}
